spring:
  application:
    name: mock-data-generator
  
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      batch-size: 16384
      linger-ms: 5
      buffer-memory: 33554432
      acks: all
      enable-idempotence: true
      compression-type: snappy
      properties:
        spring.json.add.type.headers: false
        spring.json.write.dates.as.timestamps: false

# Server configuration
server:
  port: 8081

# Data generation configuration
mockdata:
  generation:
    # Static data and SOD holdings (manual trigger via REST API)
    # POST /api/data-generation/initialize - generates both static + SOD data
    # POST /api/data-generation/static - generates accounts + instruments only  
    # POST /api/data-generation/sod-holdings - generates SOD holdings only
    
    # Dynamic data generation (continuous streams)
    prices:
      enabled: true
      interval-seconds: 5  # Every 5 seconds
    
    orders:
      enabled: true
      new-orders-interval-seconds: 30  # Every 30 seconds
      order-updates-interval-seconds: 10  # Every 10 seconds
    
    cash-movements:
      enabled: true
      interval-seconds: 120  # Every 2 minutes

# Logging configuration
logging:
  level:
    com.viewserver.mockdata: DEBUG
    com.viewserver.data: DEBUG
    org.springframework.kafka: INFO
    org.apache.kafka: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n" 