spring:
  application:
    name: view-server
  
  # Jackson configuration for JSON processing
  jackson:
    deserialization:
      fail-on-unknown-properties: false
      fail-on-null-for-primitives: false
      fail-on-numbers-for-enums: false
    serialization:
      write-dates-as-timestamps: false
      fail-on-empty-beans: false
    default-property-inclusion: non_null
    time-zone: UTC
  
  # Redis configuration
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 10000ms
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

  # Static resources configuration
  web:
    resources:
      static-locations: classpath:/static/
      cache-period: 0

  # Kafka configuration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: view-server
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest
      properties:
        spring.json.trusted.packages: "*"
      enable-auto-commit: true
      auto-commit-interval: 1000

# Server configuration
server:
  port: 8080
  
# Logging configuration
logging:
  level:
    com.viewserver: DEBUG
    org.springframework.kafka: INFO
    com.viewserver.data: DEBUG
    org.springframework.data.redis: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: view-server/view-server.log
    
# Management endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always 