spring:
  application:
    name: view-server
  
  # Redis configuration
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    
  # Jackson configuration for LocalDateTime
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
      
  # Kafka consumer configuration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: view-server
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 1000

# Server configuration
server:
  port: 8080
  
# Logging configuration
logging:
  level:
    com.viewserver: DEBUG
    org.springframework.kafka: INFO
    com.viewserver.data: DEBUG
    org.springframework.data.redis: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    
# Management endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always 